### PR TITLE
Road map update

### PR DESCRIPTION
**Pull request by wpotrzebowski**
Opening PR so it easier to see what has changed. It will be updated

### CODE REVIEW

**Comment by wpotrzebowski** [comment]
Looking at https://github.com/SasView/sasview/issues?q=is%3Aissue+is%3Aopen+label%3A%22Feature+Request%22 for new items to add to road map

**Comment by wpotrzebowski** [comment]
Potential items: 
easy data export
plotting refactoring
refine the range bars selection range
corfunc improvements (hard block volume fraction,  average soft block thickness)
Unit tests (Serialisation and deserialisation)
Resolution option from the start on theory models
Slider option for parameters
Q slicer option
Improve  Box Sum slicer: not just summing up, but integrating the peak in the defined box by a 2D gaussian fit

**Comment by butlerpd** [comment]
Other thoughts:
* Handling of multiple data sets, particularly in NXcanSAS files (particularly for things like multiple detectors in 2D or multiple magnetic cross sections in 2D (i.e.: up up; down down; up down; down up).
* Separate data loader (and/or units) package
* including C compiler for mac? and/or move to sasmodels rather than sasview?
* Generic scattering calculator updates for eventual fitting of S(Q)
  * validation of all options for calculating I(Q)
  * Adding new I(Q) calculation option (Sponge? Golden Vector? Other?)
  * Adding beta factor calculation? Adding output for an F(Q) output

**Comment by smk78** [comment]
In addition to @wpotrzebowski list above:

Bugs/Problems:
- Complete feature parity in 5.x (eg, #1763)
- Fix remaining issues with constrained/simultaneous fits (#2004, #1588, #1376, #621)
- Add smearing to Save/Load Project & Reports

New Features:
- ‘Bite the bullet’ on handling volume fraction in models with S(Q) (Sasmodels #232)
- Implement User-provided resolution functions (eg, for TOF-SANS/SESANS) (#1497)
- Implement some support for handling multiple scattering (Sasmodels #246)
- Implement FFSAS as an analysis

Model Issues:
- Fix Pringle-Schmidt helix model and implement helical ribbon model (Sasmodels #135, #417)
- Fix issues with paracrystal models (Sasmodels #284, #289, #384)

Bigger pieces of work:
- Complete the separation of Sascalc from Sasgui
- Finish integration of the SASfit model library
- Implement the McSAS optimiser within SasView (label:"McSAS Integration Project")
- Implement the generic Ornstein-Zernicke (O-Z) Solver from SASfit
- Implement the local monodisperse approximation (LMA) for P@S models applied to concentrated colloids
- Implement PRISM functionality (https://pyprism.readthedocs.io/en/latest/)  
- Implement calculation of scattering from arbitrary shapes
- Implement calculation of 2D scattering patterns from oriented systems (https://doi.org/10.1107/S1600576717005179) 
- Implement custom workflows (such as: finding the contrast match point from a series of datasets; pulling out the nuclear vs magnetic scattering from several polarised 2D datasets or from 1D cuts parallel and perpendicular to the field, etc.)
- Clean up resolution calculations (ensure each q has a basis of support in calculated q values, then submit that full vector to the calculator as one piece; the current method computes the end pieces separately from the middle)
- Implement adaptive numerical integration schemes
- Implement MC integration for high dimensional polydispersity integrals
- Implement SVD-like analysis for mixtures of unknown shapes 
- (potential collaboration with MaxIV)
- Allow for structure factor interactions between oriented particles
- Enable computational code to run on clusters and implement an intelligent launcher/scheduler to make use of the cluster transparent to the user
- Provide a Web UI to SasView
- Implement headless operation and realtime analysis workflows
- Implement intelligent/automatic model selection (eg, using AI and/or Bayesian approaches)
- Implement intelligent limits/help
- Add ASAXS support

**Comment by butlerpd** [comment]
I'm removing the 2022 community meeting as I believe we agreed it was too late to provide anything.

**Comment by butlerpd** [comment]
### COLLECTED LIST OF ITEMS NOT YET IN THE ROADMAP
- [ ] Refactor the way plotting is tied to data and fitting etc
- [ ] Refactor reporting and exporting of perspective data
- [ ] Refactoring of project/analysis Saving and Loading
- [ ] Slicer refactoring (including box sum, new slicers,2D peak fit for centroid etc)
- [ ] Improve magnetic SANS usability/utility
- [ ] upgrade model marketplace
- [ ] refactor handling  of multiple data sets for various use cases/workflows in conjunction with NXcanSAS
- [ ] Add support for handling multiple scattering
- [ ] Extend available integration options such as adaptive, MC integration etc
- [ ] Implement custom workflows (such as: finding the contrast match point from a series of datasets; pulling out the nuclear vs magnetic scattering from several polarised 2D datasets or from 1D cuts parallel and perpendicular to the field, etc.)
- [ ] P/*S computation enhancements (adding locally monodisperse approx.; fix volume fraction issue, etc.)

### Not sure where these go:
* Implement calculation of 2D scattering patterns from oriented systems (https://doi.org/10.1107/S1600576717005179)
  * This looks like it would be another builder/engine for the general scattering calculator like sponge and mcsim and the current oriented engine (which may be wrong). If so this should be part of that bullet in the roadmap rather than a separate bullet.
* Clean up resolution calculations (ensure each q has a basis of support in calculated q values, then submit that full vector to the calculator as one piece; the current method computes the end pieces separately from the middle)
  * while no doubt useful, as stated it seems much too granular for the roadmap?

### Not sure these still make sense?
* Is there anything else we need to do with SASfit to  close that out? I thought we were done?
* Steve has "Allow for structure factor interactions between oriented particles." Does the theory for this exist? If not we should probably not be putting on the roadmap that we will "do it'

**Pull request merged**
